### ISSUE TITLE
Remove WBTC

### ISSUE THREAD

**Issue by marcuswin** [ong/awesome-decentralized-finance#12]
I think that we can remove WBTC, because it's just wrapper over BTC for using in Ethereum chain. Price of BTC is high volatile, which makes this coin a not stable.

**Comment by ong** [comment]
WBTC is rightly not stable relative to USD, but it should be judged instead by its 1:1 peg to BTC. WBTC could become an important part of the DeFi stack since it allows BTC to be used in conjunction with the other primitives, so I am going to leave it on the list.

(BTW: Thanks for your PR and the associated improvements!)
